# Generated by Django 5.0.7 on 2024-07-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_techusedtagmodel_projectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
