# Generated by Django 5.0.7 on 2024-07-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_projectmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
