# Generated by Django 5.0.7 on 2024-08-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_achievementmodel_alter_projectmodel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementmodel',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
