# Generated by Django 5.0.7 on 2024-08-08 15:06

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_projectmodel_document_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodel',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
